### ISSUE TITLE
Is the implementation wrong?

### ISSUE THREAD

**Issue by ranery** [sramshetty/mixture-of-depths#5]
sorted_indices = torch.argsort(topk_indices)

should be

sorted_indices = torch.sort(topk_indices)

Right?

**Comment by sramshetty** [comment]
Nice catch, sorry about that!

I do in fact need the `argsort()` output for the gather [here](https://github.com/sramshetty/mixture-of-depths/blob/485e14da321d8923c15a5d2e56c8ddfb88f9db7d/mixture_of_depths/routing_transformer.py#L313), but like you mentioned the gather for `x` and `y` should be the sorted indices themselves.

Let me know if this makes sense to you, and thanks for pointing it out.

**Comment by ranery** [comment]
That makes sense now!

I also used:

sorted_indices, index = torch.sort(topk_indices, dim=1)

so that the sorted_indices could be used for x gather and the index could be used for output gather.
